# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Course(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, day: str=None, start_time: int=None, end_time: int=None):  # noqa: E501
        """Course - a model defined in Swagger

        :param name: The name of this Course.  # noqa: E501
        :type name: str
        :param day: The day of this Course.  # noqa: E501
        :type day: str
        :param start_time: The start_time of this Course.  # noqa: E501
        :type start_time: int
        :param end_time: The end_time of this Course.  # noqa: E501
        :type end_time: int
        """
        self.swagger_types = {
            'name': str,
            'day': str,
            'start_time': int,
            'end_time': int
        }

        self.attribute_map = {
            'name': 'name',
            'day': 'day',
            'start_time': 'startTime',
            'end_time': 'endTime'
        }

        self._name = name
        self._day = day
        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'Course':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Course of this Course.  # noqa: E501
        :rtype: Course
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Course.


        :return: The name of this Course.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Course.


        :param name: The name of this Course.
        :type name: str
        """

        self._name = name

    @property
    def day(self) -> str:
        """Gets the day of this Course.


        :return: The day of this Course.
        :rtype: str
        """
        return self._day

    @day.setter
    def day(self, day: str):
        """Sets the day of this Course.


        :param day: The day of this Course.
        :type day: str
        """

        self._day = day

    @property
    def start_time(self) -> int:
        """Gets the start_time of this Course.


        :return: The start_time of this Course.
        :rtype: int
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: int):
        """Sets the start_time of this Course.


        :param start_time: The start_time of this Course.
        :type start_time: int
        """

        self._start_time = start_time

    @property
    def end_time(self) -> int:
        """Gets the end_time of this Course.


        :return: The end_time of this Course.
        :rtype: int
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: int):
        """Sets the end_time of this Course.


        :param end_time: The end_time of this Course.
        :type end_time: int
        """

        self._end_time = end_time
